name: OpenWrt x86_64 Daed + Passwall2 Build

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04
    # 必须赋予写权限，否则无法创建 Release
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install bc binutils-gold bison build-essential ccache ecj fastjar file flex g++ gawk gcc-arm* gettext git help2man libbsd-dev libelf-dev liblzma-dev libncurses-dev libssl-dev mtd-utils meson mold mtd-utils ninja-build pbzip2 pigz pkg-config python3-dev python3-setuptools rsync subversion swig texinfo time u-boot-tools unzip wget xsltproc xxd zlib1g-dev zstd clang llvm npm cmake
        sudo npm install -g pnpm
    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git -b v25.12.4 openwrt
        cd openwrt
        git clone https://github.com/QiuSimons/luci-app-daed package/dae
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        sed -i 's/192.168.1.1/192.168.5.1/g' package/base-files/files/bin/config_generate

    - name: Apply .config
      run: |
        cd openwrt
        cat > .config << 'EOF'
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_DEVICE_generic=y
        # 关闭不需要的归档格式
        # CONFIG_TARGET_ROOTFS_CPIOGZ is not set
        # CONFIG_TARGET_ROOTFS_TARGZ is not set
        # 开启 Hyper-V VHDX 镜像输出
        CONFIG_TARGET_IMAGES_VHDX=y
        # 修改分区大小 (单位: MiB)
        CONFIG_TARGET_KERNEL_PARTSIZE=200
        CONFIG_TARGET_ROOTFS_PARTSIZE=300
        CONFIG_DEVEL=y
        CONFIG_BPF_TOOLCHAIN_HOST=y
        CONFIG_BPF_TOOLCHAIN_HOST_PATH="/usr/lib/llvm-18/bin"
        CONFIG_PACKAGE_kmod-usb-core=y
        CONFIG_PACKAGE_kmod-usb-net=y
        CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
        CONFIG_PACKAGE_kmod-usb-ohci=y
        CONFIG_PACKAGE_kmod-usb-ohci-pci=y
        CONFIG_PACKAGE_kmod-usb-serial=y
        CONFIG_PACKAGE_kmod-usb-storage=y
        CONFIG_PACKAGE_kmod-usb-storage-extras=y
        CONFIG_PACKAGE_kmod-usb2=y
        CONFIG_PACKAGE_kmod-usb3=y
        CONFIG_PACKAGE_luci=y
        CONFIG_LUCI_LANG_zh_Hans=y
        CONFIG_PACKAGE_luci-app-ttyd=y
        CONFIG_PACKAGE_luci-app-daed=y
        CONFIG_DEVEL=y
        CONFIG_KERNEL_DEBUG_INFO=y
        CONFIG_KERNEL_DEBUG_INFO_REDUCED=n
        CONFIG_KERNEL_DEBUG_INFO_BTF=y
        CONFIG_KERNEL_CGROUPS=y
        CONFIG_KERNEL_CGROUP_BPF=y
        CONFIG_KERNEL_BPF_EVENTS=y
        CONFIG_BPF_TOOLCHAIN_HOST=y
        CONFIG_KERNEL_XDP_SOCKETS=y
        CONFIG_PACKAGE_kmod-xdp-sockets-diag=y
        EOF
        make defconfig    
        make download -j8
        make -j$(nproc) || make -j1 V=s

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-x86_64-Daed-Passwall2
        path: openwrt/bin/targets
       # 3. 发布到 GitHub Releases
    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        # 要上传的文件路径，支持通配符
        files: dist/my-package-*.tar.gz
        # 自动根据 commit 记录生成 Release 日志
        generate_release_notes: true
